const puppeteer=require('puppeteer-core');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:'new',args:['--no-sandbox','--ignore-gpu-blocklist']});
const p=await b.newPage();await p.setViewport({width:1200,height:800});const errs=[];p.on('pageerror',e=>errs.push(String(e).slice(0,140)));
await p.goto(process.argv[2],{waitUntil:'domcontentloaded'});await sleep(14000);
await p.evaluate(()=>{window.__ap.toggleFree();window.__rec=[];(function f(){const q=__apW.probe;__rec.push([performance.now(),q.fs,q.fov||0,q.punch||0,q.boostAmt||0,q.curSpeed||0]);requestAnimationFrame(f)})();
 window.__dir=()=>{const q=__apW.probe;const look=Math.max(8,q.fs*0.9),tz=q.fz-look,tx=q.roadX(tz);let hd=Math.atan2(-(tx-q.fx),-(tz-q.fz)),e=hd-q.fh;e=Math.atan2(Math.sin(e),Math.cos(e));return e>0.04?-1:e<-0.04?1:0}});
let held=0,done=false;(async()=>{while(!done){const d=await p.evaluate(()=>__dir());if(d!==held){if(held===-1)await p.keyboard.up('ArrowLeft');if(held===1)await p.keyboard.up('ArrowRight');if(d===-1)await p.keyboard.down('ArrowLeft');if(d===1)await p.keyboard.down('ArrowRight');held=d}await sleep(35)}})();
await sleep(1200);const mark=async fn=>{await p.evaluate(()=>{__rec.m=__rec.length});await fn();return p.evaluate(()=>__rec.slice(__rec.m))};
await p.keyboard.down('ArrowUp');
let r=await mark(()=>sleep(11000));const hud=a=>Math.round(a*6);
const norm={topHUD:hud(Math.max(...r.map(a=>a[1]))),fovAtTop:+r[r.length-1][2].toFixed(1),speedFxish:+r[r.length-1][5].toFixed(1)};
const fov0=r[0][2];
await p.keyboard.down('Shift');
r=await mark(()=>sleep(5000));
const t0=r[0][0];const at=s=>{const x=r.find(a=>a[0]-t0>=s);return x?hud(x[1]):null};
const boost={hud_0s:at(0),hud_0_3s:at(300),hud_0_6s:at(600),hud_1s:at(1000),hud_2s:at(2000),hud_4s:at(4000),topHUD:hud(Math.max(...r.map(a=>a[1]))),peakPunch:+Math.max(...r.map(a=>a[3])).toFixed(2),fovPeak:+Math.max(...r.map(a=>a[2])).toFixed(1),fovHeld:+r[r.length-1][2].toFixed(1)};
await p.keyboard.up('Shift');
r=await mark(()=>sleep(3000));
const rel={hudAfterRelease3s:hud(r[r.length-1][1])};
done=true;await p.keyboard.up('ArrowUp');
console.log(JSON.stringify({baseFov:+fov0.toFixed(1),normal:norm,boost,release:rel,errors:errs}));await sleep(300);await b.close()})();
